### ISSUE TITLE
What about multiple versions per day?

### ISSUE THREAD

**Issue by mathiasbynens** [evilpie/Impfquotenmonitoring#1]
On 2021-01-19 there were at least two versions published: first https://github.com/mathiasbynens/covid-19-vaccinations-germany/commit/a63458b00cdbe827cb33f7e754ccff400a5e7810 (empty cells instead of zeroes) and later https://github.com/mathiasbynens/covid-19-vaccinations-germany/commit/23fb5f1a41938c53549e96c3f320fc58d719bbd0 (zeroes added + some data adjusted). Unfortunately I don't have the Excel files, but it would be good to know if a) this project aims to collect multiple versions as well, and b) what the naming scheme would be.

**Comment by evilpie** [comment]
I decided to collect multiple versions with -2, -3 etc.

**Comment by mathiasbynens** [comment]
> I decided to collect multiple versions with -2, -3 etc.

Sounds good. Heads-up: that's not what https://github.com/evilpie/Impfquotenmonitoring/blob/master/update.py seems to be doing, currently.

**Comment by mathiasbynens** [comment]
Ooh, it does, never mind :) Thanks!
