### ISSUE TITLE
Automate updates

### ISSUE THREAD

**Issue by mathiasbynens** [evilpie/Impfquotenmonitoring#2]
We could set up a GitHub Action that periodically checks for updates and pulls in the new spreadsheet.

Alternatively, we could piggyback off of the existing automation for https://github.com/mathiasbynens/covid-19-vaccinations-germany by uncommenting this line: https://github.com/mathiasbynens/covid-19-vaccinations-germany/blob/c9ba197eb1040496559a9a95334eaa2282b03592/.gitignore#L1 This would ensure that the spreadsheet is included in future automated commits like https://github.com/mathiasbynens/covid-19-vaccinations-germany/commit/c9ba197eb1040496559a9a95334eaa2282b03592. One could then get all the different `xlsx` files by navigating the Git history.

**Comment by evilpie** [comment]
Great idea. I hadn't used this feature before, really cool that you can use cron. I tried copying some of your stuff, but it seems like it's running in the wrong directory?

```
python: can't open file '/home/runner/work/Impfquotenmonitoring/Impfquotenmonitoring/update.py': [Errno 2] No such file or directory
```

**Comment by evilpie** [comment]
Ok cool. I think I got it working now. Let's see when the first automated update runs :rocket:

**Comment by evilpie** [comment]
Seems to work now. Thanks again for pointing this out.
