### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by evilpie** [evilpie/Impfquotenmonitoring#4]
It looks like we are still missing the raw data for:

- [x] - 2020-12-27
- [x] - 2020-12-28
- [x] - 2020-12-29
- [x] - 2020-12-31
- [x] - 2020-01-01
- [ ] - 2020-01-09 (weekend?)
- [x] - 2020-01-10
- [ ] - 2020-01-16

**Comment by evilpie** [comment]
I found some additional files thanks to archive.org :heart:. The first two files seem a bit suspicious, but this is best we have for now. 454e40f1682b0bf2326899e38877084e949c744a

**Comment by evilpie** [comment]
https://web.archive.org/web/*/https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/* might be helpful for finding more missing data.

**Comment by mathiasbynens** [comment]
https://github.com/ard-data/2020-rki-impf-archive/tree/master/data/0_original seems to have some of the missing ones (based on the file names)

**Comment by evilpie** [comment]
I imported those files. I suspect date for the 21-01-09 (publishing date 21-01-10) and  21-01-16 (publishing date 21-01-17)   just doesn't exist.
